name = "notification-worker"
main = "src/index.ts"
compatibility_flags = ["nodejs_compat"]
compatibility_date = "2024-12-01"

[[queues]]
binding = "OFFLINE_DELIVERY_QUEUE"
queue = "offline-delivery-staging"

[[queues]]
binding = "EMAIL_QUEUE"
queue = "email-staging"

[observability]
enabled = true
