name = "notification-worker"
main = "src/index.ts"
compatibility_flags = ["nodejs_compat"]
compatibility_date = "2024-12-01"

[[queues.producers]]
binding = "OFFLINE_DELIVERY_QUEUE"
queue = "offline-delivery-dev"

[[queues.producers]]
binding = "EMAIL_QUEUE"
queue = "email-dev"

[env.staging]
[[env.staging.queues.producers]]
binding = "OFFLINE_DELIVERY_QUEUE"
queue = "offline-delivery-staging"

[[env.staging.queues.producers]]
binding = "EMAIL_QUEUE"
queue = "email-staging"

[env.production]
[[env.production.queues.producers]]
binding = "OFFLINE_DELIVERY_QUEUE"
queue = "offline-delivery-prod"

[[env.production.queues.producers]]
binding = "EMAIL_QUEUE"
queue = "email-prod"

[observability]
enabled = true
