name = "backup-worker"
main = "src/index.ts"
compatibility_flags = ["nodejs_compat"]
compatibility_date = "2024-12-01"

[vars]
B2_ENDPOINT = "s3.us-west-004.backblazeb2.com"
B2_REGION = "us-west-004"
B2_BUCKET_NAME = "qyx-attachments-dev"

[triggers]
crons = ["0 2 * * *", "0 3 * * *"]
